### ISSUE TITLE
TypeError when accessing class name from CSS module

### ISSUE THREAD

**Issue by fenech** [Jimdo/typings-for-css-modules-plugin#12] opened 2016-08-23 15:57 UTC
I have the following (simplified!) CSS file:

```
.axis {
    display: initial;
}
```

It builds into the following:

```
.Axis__axis___33NKW {
    display: initial;
}
```

The plugin produces the following definition file:

```
export interface IAxisCss {
  'axis': string;
}
declare const styles: IAxisCss;

export default styles;
```

I am trying to import the module using `import styles from "./Axis.css";` and then use `styles.axis` to get my generated CSS class name. When I do this, I get a `TypeError: "Axis_css_1.default is undefined"`. It seems like the type definition isn't matching up with what webpack has produced...

I managed to get it to work by importing like this: `import * as styles from "./Axis.css";` and then using `(styles as any).axis` but clearly this isn't the intended way to do things!

My webpack loader config looks like this:

```
{
    test: /\.css$/,
    loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
}
```

Any idea why this is happening and what I can do to fix it?

**Comment by danroberts** [comment] 2016-08-23 21:39
I'm also having this problem. It seems to be from some quick debugging that webpack does not put the namespace on default, but rather directly on the top level element, in this case, Axis_css_1.axis, rather than Axis_css_1.default.axis, but I can't figure out where the 'default' is coming from

**Comment by timse** [comment] 2016-08-24 08:13
I will try to reproduce this, and come back to you! (my first guess would be it might be related to the ExtractTextPlugin but I will try this first!

**Comment by timse** [comment] 2016-08-29 09:15
I am currently unable to reproduce this. Could one of you @fenech @danroberts please provide me with an example where this happens?

**Comment by fenech** [comment] 2016-08-29 14:15
@timse I've created a small repo here: https://github.com/fenech/typings-css-modules

**Comment by danroberts** [comment] 2016-08-29 18:39
I spent some time this weekend trying to pull out the interface declaration style and integrating it into Quarmy/typed-css-modules so that I could use the webpack loader, and I encountered the same error after a totally different implementation. 

I'm thinking this is due to something in the webpack css module loader, which creates an object with a top level namespace and then all css declarations as children. 

With the additional loader for typescript, the top level namespace is adding a child for each exported property, which then contains the css declarations.

I.e.

`.className {
  background-color: red;
}`

The css module loader turns that Filename_css_1.className, but with the exported interface module, webpack converts that variable into Filename_css_1.exported_variable_name.className

**Comment by fenech** [comment] 2016-08-29 20:42
@danroberts so what is the alternative to using the webpack CSS module loader? 

If it's simple to get my mini example to work, that'd be great!

**Comment by danroberts** [comment] 2016-08-29 21:01
I'm speculating at this point, but I think we need to somehow tap into the css module loader and add some additional namespace like 'default', or 'styles' to the css loader export.

**Comment by timse** [comment] 2016-08-30 06:49
hey, thanks so much for the repo @fenech. I got it to work and the explanation is kind of weird.

Basically if you add `babel-loader` after the `ts-loader` in your webpack config and set the target of the typescript compiler to `es6` it works.

install babel-loader `npm install -D babel-loader` and add it to the ts-loaders

``` js
loaders: [
    "babel-loader",
    "ts-loader"
]
```

the tsconfig.json file should look something like this:

``` json
{
    "compilerOptions": {
        "target": "es6"
    }
}
```

Now for the problem:
Basically the type-decleration that I create has a default export which is the interface that contains all the classNames. So having just typescript as the compiler means that it will compile javascript expecting a default export from the module that is generated by css-module-loader.
However this is not the case. Thus it fails trying to access `styles.default.foo`.

The solution I am proposing here is far from being perfect as it requires you to have your ts-compiled code being compiled again by babel (we do this in our project as we use `async/await` so we didnt find this error in the first place - sorry for not checking this more properly).

Babel somehow takes care of checking if an actual `default` export exists and otherwise just uses whatever is on `module.export` which is probably what the `css-module-loader` exposes.

I will see if there is any way we can have this work without babel, but for now i guess its the easiest way!

**Comment by fenech** [comment] 2016-08-30 09:53
OK it looks as though the issue is with using CommonJS modules. Based on the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/compiler-options.html) I came to the following conclusions:
- When `target` is unspecified is `tsconfig.json`, the default value is `"ES5"`. 
- The value of `module` is then determined as follows: `(target === "ES6" ? "ES6" : "CommonJS")`.

So, the config that works is essentially:

```
"compilerOptions": {
    "module": "es6",
    "target": "es6"
},
```

I found that with this configuration, Babel is then needed to prevent errors like: 

```
SyntaxError: import declarations may only appear at top level of a module
```

---

In my real project, I found that using ES6 modules caused the TypeScript compiler to complain, e.g.:

```
error TS2307: Cannot find module 'reselect'
```

I managed to resolve this by adding this :

```
"compilerOptions": {
    // ...
    "moduleResolution": "node"
}
```

**Comment by timse** [comment] 2016-09-23 09:56
Hey sorry for my late reply, but I was checking all the issues that occured and went for a very different solution by rewriting the plugin to be a drop in replacement for the css-loader, see here: https://github.com/Jimdo/typings-for-css-modules-loader.

I will therefore close this issue and hope you give the loader a try :)!

**Closed as completed by timse** 2016-09-23 09:56 UTC
